[build]
builder = "nixpacks"
buildCommand = "rm -rf node_modules package-lock.json && npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/test"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
FORCE_REBUILD = "true" 